"""Static reference data seeded once: HS codes and target markets."""

from __future__ import annotations

# (code, level, parent, en, ar, sector)
HS_CODES: list[tuple[str, int, str | None, str, str, str]] = [
    # Plastics (chapter 39)
    ("39", 2, None, "Plastics and articles thereof", "اللدائن ومصنوعاتها", "plastics"),
    (
        "3917",
        4,
        "39",
        "Tubes, pipes and hoses of plastics",
        "أنابيب وخراطيم من اللدائن",
        "plastics",
    ),
    (
        "391721",
        6,
        "3917",
        "Rigid tubes/pipes of ethylene polymers",
        "أنابيب صلبة من بوليمرات الإيثيلين",
        "plastics",
    ),
    (
        "391723",
        6,
        "3917",
        "Rigid tubes/pipes of vinyl chloride polymers",
        "أنابيب صلبة من بوليمرات كلوريد الفينيل",
        "plastics",
    ),
    (
        "391740",
        6,
        "3917",
        "Fittings for plastic tubes and pipes",
        "وصلات لأنابيب اللدائن",
        "plastics",
    ),
    (
        "3920",
        4,
        "39",
        "Plates, sheets and film of plastics, non-cellular",
        "ألواح وصفائح وأغشية من اللدائن غير خلوية",
        "plastics",
    ),
    ("392010", 6, "3920", "Film of ethylene polymers", "أغشية من بوليمرات الإيثيلين", "plastics"),
    ("392020", 6, "3920", "Film of propylene polymers", "أغشية من بوليمرات البروبيلين", "plastics"),
    (
        "3923",
        4,
        "39",
        "Articles for conveyance/packing, of plastics",
        "أدوات نقل وتعبئة من اللدائن",
        "plastics",
    ),
    (
        "392321",
        6,
        "3923",
        "Sacks and bags of ethylene polymers",
        "أكياس من بوليمرات الإيثيلين",
        "plastics",
    ),
    ("392329", 6, "3923", "Sacks and bags of other plastics", "أكياس من لدائن أخرى", "plastics"),
    (
        "392330",
        6,
        "3923",
        "Carboys, bottles and flasks of plastics",
        "قوارير وزجاجات من اللدائن",
        "plastics",
    ),
    (
        "392390",
        6,
        "3923",
        "Other packing articles of plastics",
        "أدوات تعبئة أخرى من اللدائن",
        "plastics",
    ),
    # Food (chapters 04, 08, 17, 19, 20)
    ("04", 2, None, "Dairy produce; eggs; honey", "منتجات الألبان؛ بيض؛ عسل", "food"),
    ("0401", 4, "04", "Milk and cream, not concentrated", "حليب وقشدة غير مركزة", "food"),
    ("040110", 6, "0401", "Milk and cream, fat content ≤1%", "حليب وقشدة بنسبة دهن ≤1%", "food"),
    ("0406", 4, "04", "Cheese and curd", "جبن ولبن متخثر", "food"),
    ("040690", 6, "0406", "Cheese, other", "جبن، أنواع أخرى", "food"),
    ("08", 2, None, "Edible fruit and nuts", "فواكه وثمار صالحة للأكل", "food"),
    ("0804", 4, "08", "Dates, figs, pineapples, avocados", "تمور وتين وأناناس وأفوكادو", "food"),
    ("080410", 6, "0804", "Dates, fresh or dried", "تمور طازجة أو مجففة", "food"),
    ("17", 2, None, "Sugars and sugar confectionery", "سكر ومصنوعات سكرية", "food"),
    ("1704", 4, "17", "Sugar confectionery, no cocoa", "حلويات سكرية بدون كاكاو", "food"),
    ("170490", 6, "1704", "Sugar confectionery, other", "حلويات سكرية، أنواع أخرى", "food"),
    ("19", 2, None, "Preparations of cereals, flour, bakery", "محضرات حبوب ودقيق ومخبوزات", "food"),
    ("1905", 4, "19", "Bread, pastry, cakes, biscuits", "خبز ومعجنات وبسكويت", "food"),
    ("190531", 6, "1905", "Sweet biscuits", "بسكويت حلو", "food"),
    ("190590", 6, "1905", "Bakers' wares, other", "منتجات مخابز أخرى", "food"),
    ("20", 2, None, "Preparations of vegetables and fruit", "محضرات خضروات وفواكه", "food"),
    (
        "2008",
        4,
        "20",
        "Fruit and nuts, otherwise prepared",
        "فواكه وثمار محضرة بطريقة أخرى",
        "food",
    ),
    ("200899", 6, "2008", "Fruit/nuts prepared, other", "فواكه محضرة، أنواع أخرى", "food"),
    ("2009", 4, "20", "Fruit and vegetable juices", "عصائر فواكه وخضروات", "food"),
    (
        "200980",
        6,
        "2009",
        "Juice of other single fruit/vegetable",
        "عصير فاكهة أو خضار مفرد",
        "food",
    ),
]

# (iso2, en, ar, region, currency, language, gcc, eu, us)
MARKETS: list[tuple[str, str, str, str, str, str, bool, bool, bool]] = [
    ("IN", "India", "الهند", "South Asia", "INR", "hi", False, False, False),
    ("EG", "Egypt", "مصر", "North Africa", "EGP", "en", False, False, False),
    ("DE", "Germany", "ألمانيا", "Europe", "EUR", "en", False, True, False),
    ("AE", "United Arab Emirates", "الإمارات", "GCC", "AED", "en", True, False, False),
    ("QA", "Qatar", "قطر", "GCC", "QAR", "en", True, False, False),
    ("KW", "Kuwait", "الكويت", "GCC", "KWD", "en", True, False, False),
    ("US", "United States", "الولايات المتحدة", "North America", "USD", "en", False, False, True),
    ("ES", "Spain", "إسبانيا", "Europe", "EUR", "es", False, True, False),
    ("BR", "Brazil", "البرازيل", "South America", "BRL", "pt", False, False, False),
    ("FR", "France", "فرنسا", "Europe", "EUR", "fr", False, True, False),
]
